/*
divar_interface/open_platform/chatapi/chatapi.proto

Testing LimitedAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package kenarapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID/kenarapi"
)

func Test_kenarapi_LimitedAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test LimitedAPIService PaymentGetBalance", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.LimitedAPI.PaymentGetBalance(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LimitedAPIService PaymentGetPostPricing", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var postToken string

		resp, httpRes, err := apiClient.LimitedAPI.PaymentGetPostPricing(context.Background(), postToken).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LimitedAPIService PaymentGetTransaction", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.LimitedAPI.PaymentGetTransaction(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LimitedAPIService PaymentReorderPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var postToken string

		resp, httpRes, err := apiClient.LimitedAPI.PaymentReorderPost(context.Background(), postToken).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
