/*
API کنار

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kenarapi

import (
	"encoding/json"
)

// checks if the FinderGetUserBusinessesResponseBusiness type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FinderGetUserBusinessesResponseBusiness{}

// FinderGetUserBusinessesResponseBusiness struct for FinderGetUserBusinessesResponseBusiness
type FinderGetUserBusinessesResponseBusiness struct {
	// توضیحات کسب‌وکار
	BrandDescription *string `json:"brand_description,omitempty"`
	// نام کسب‌وکار/برند
	BrandName *string `json:"brand_name,omitempty"`
	// شناسه توکن کسب‌وکار
	BusinessToken *string `json:"business_token,omitempty"`
	BusinessType *BaseBusinessType `json:"business_type,omitempty"`
	UserRole *PremiumPanelUserRole `json:"user_role,omitempty"`
}

// NewFinderGetUserBusinessesResponseBusiness instantiates a new FinderGetUserBusinessesResponseBusiness object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFinderGetUserBusinessesResponseBusiness() *FinderGetUserBusinessesResponseBusiness {
	this := FinderGetUserBusinessesResponseBusiness{}
	return &this
}

// NewFinderGetUserBusinessesResponseBusinessWithDefaults instantiates a new FinderGetUserBusinessesResponseBusiness object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFinderGetUserBusinessesResponseBusinessWithDefaults() *FinderGetUserBusinessesResponseBusiness {
	this := FinderGetUserBusinessesResponseBusiness{}
	return &this
}

// GetBrandDescription returns the BrandDescription field value if set, zero value otherwise.
func (o *FinderGetUserBusinessesResponseBusiness) GetBrandDescription() string {
	if o == nil || IsNil(o.BrandDescription) {
		var ret string
		return ret
	}
	return *o.BrandDescription
}

// GetBrandDescriptionOk returns a tuple with the BrandDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FinderGetUserBusinessesResponseBusiness) GetBrandDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.BrandDescription) {
		return nil, false
	}
	return o.BrandDescription, true
}

// HasBrandDescription returns a boolean if a field has been set.
func (o *FinderGetUserBusinessesResponseBusiness) HasBrandDescription() bool {
	if o != nil && !IsNil(o.BrandDescription) {
		return true
	}

	return false
}

// SetBrandDescription gets a reference to the given string and assigns it to the BrandDescription field.
func (o *FinderGetUserBusinessesResponseBusiness) SetBrandDescription(v string) {
	o.BrandDescription = &v
}

// GetBrandName returns the BrandName field value if set, zero value otherwise.
func (o *FinderGetUserBusinessesResponseBusiness) GetBrandName() string {
	if o == nil || IsNil(o.BrandName) {
		var ret string
		return ret
	}
	return *o.BrandName
}

// GetBrandNameOk returns a tuple with the BrandName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FinderGetUserBusinessesResponseBusiness) GetBrandNameOk() (*string, bool) {
	if o == nil || IsNil(o.BrandName) {
		return nil, false
	}
	return o.BrandName, true
}

// HasBrandName returns a boolean if a field has been set.
func (o *FinderGetUserBusinessesResponseBusiness) HasBrandName() bool {
	if o != nil && !IsNil(o.BrandName) {
		return true
	}

	return false
}

// SetBrandName gets a reference to the given string and assigns it to the BrandName field.
func (o *FinderGetUserBusinessesResponseBusiness) SetBrandName(v string) {
	o.BrandName = &v
}

// GetBusinessToken returns the BusinessToken field value if set, zero value otherwise.
func (o *FinderGetUserBusinessesResponseBusiness) GetBusinessToken() string {
	if o == nil || IsNil(o.BusinessToken) {
		var ret string
		return ret
	}
	return *o.BusinessToken
}

// GetBusinessTokenOk returns a tuple with the BusinessToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FinderGetUserBusinessesResponseBusiness) GetBusinessTokenOk() (*string, bool) {
	if o == nil || IsNil(o.BusinessToken) {
		return nil, false
	}
	return o.BusinessToken, true
}

// HasBusinessToken returns a boolean if a field has been set.
func (o *FinderGetUserBusinessesResponseBusiness) HasBusinessToken() bool {
	if o != nil && !IsNil(o.BusinessToken) {
		return true
	}

	return false
}

// SetBusinessToken gets a reference to the given string and assigns it to the BusinessToken field.
func (o *FinderGetUserBusinessesResponseBusiness) SetBusinessToken(v string) {
	o.BusinessToken = &v
}

// GetBusinessType returns the BusinessType field value if set, zero value otherwise.
func (o *FinderGetUserBusinessesResponseBusiness) GetBusinessType() BaseBusinessType {
	if o == nil || IsNil(o.BusinessType) {
		var ret BaseBusinessType
		return ret
	}
	return *o.BusinessType
}

// GetBusinessTypeOk returns a tuple with the BusinessType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FinderGetUserBusinessesResponseBusiness) GetBusinessTypeOk() (*BaseBusinessType, bool) {
	if o == nil || IsNil(o.BusinessType) {
		return nil, false
	}
	return o.BusinessType, true
}

// HasBusinessType returns a boolean if a field has been set.
func (o *FinderGetUserBusinessesResponseBusiness) HasBusinessType() bool {
	if o != nil && !IsNil(o.BusinessType) {
		return true
	}

	return false
}

// SetBusinessType gets a reference to the given BaseBusinessType and assigns it to the BusinessType field.
func (o *FinderGetUserBusinessesResponseBusiness) SetBusinessType(v BaseBusinessType) {
	o.BusinessType = &v
}

// GetUserRole returns the UserRole field value if set, zero value otherwise.
func (o *FinderGetUserBusinessesResponseBusiness) GetUserRole() PremiumPanelUserRole {
	if o == nil || IsNil(o.UserRole) {
		var ret PremiumPanelUserRole
		return ret
	}
	return *o.UserRole
}

// GetUserRoleOk returns a tuple with the UserRole field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FinderGetUserBusinessesResponseBusiness) GetUserRoleOk() (*PremiumPanelUserRole, bool) {
	if o == nil || IsNil(o.UserRole) {
		return nil, false
	}
	return o.UserRole, true
}

// HasUserRole returns a boolean if a field has been set.
func (o *FinderGetUserBusinessesResponseBusiness) HasUserRole() bool {
	if o != nil && !IsNil(o.UserRole) {
		return true
	}

	return false
}

// SetUserRole gets a reference to the given PremiumPanelUserRole and assigns it to the UserRole field.
func (o *FinderGetUserBusinessesResponseBusiness) SetUserRole(v PremiumPanelUserRole) {
	o.UserRole = &v
}

func (o FinderGetUserBusinessesResponseBusiness) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FinderGetUserBusinessesResponseBusiness) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BrandDescription) {
		toSerialize["brand_description"] = o.BrandDescription
	}
	if !IsNil(o.BrandName) {
		toSerialize["brand_name"] = o.BrandName
	}
	if !IsNil(o.BusinessToken) {
		toSerialize["business_token"] = o.BusinessToken
	}
	if !IsNil(o.BusinessType) {
		toSerialize["business_type"] = o.BusinessType
	}
	if !IsNil(o.UserRole) {
		toSerialize["user_role"] = o.UserRole
	}
	return toSerialize, nil
}

type NullableFinderGetUserBusinessesResponseBusiness struct {
	value *FinderGetUserBusinessesResponseBusiness
	isSet bool
}

func (v NullableFinderGetUserBusinessesResponseBusiness) Get() *FinderGetUserBusinessesResponseBusiness {
	return v.value
}

func (v *NullableFinderGetUserBusinessesResponseBusiness) Set(val *FinderGetUserBusinessesResponseBusiness) {
	v.value = val
	v.isSet = true
}

func (v NullableFinderGetUserBusinessesResponseBusiness) IsSet() bool {
	return v.isSet
}

func (v *NullableFinderGetUserBusinessesResponseBusiness) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFinderGetUserBusinessesResponseBusiness(val *FinderGetUserBusinessesResponseBusiness) *NullableFinderGetUserBusinessesResponseBusiness {
	return &NullableFinderGetUserBusinessesResponseBusiness{value: val, isSet: true}
}

func (v NullableFinderGetUserBusinessesResponseBusiness) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFinderGetUserBusinessesResponseBusiness) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


