/*
API کنار

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kenarapi

import (
	"encoding/json"
)

// checks if the PaymentRenewPostBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentRenewPostBody{}

// PaymentRenewPostBody struct for PaymentRenewPostBody
type PaymentRenewPostBody struct {
	// اطلاعات تکمیلی که می‌خواهید به کنار ارسال کنید. این فیلد اختیاری است و برای رفع مغایرت‌های احتمالی در تراکنش کاربرد دارد.
	ExtraDetails *string `json:"extra_details,omitempty"`
	// یک UUID نسخه ۴ که باید برای هر پرداخت یکتا باشد. این UUID باید در سمت شما ساخته شده و در درخواست ارسال شود. اگر id ارسال‌شده قبلاً تراکنش موفق یا نیمه‌موفقی در کنار داشته باشد، خطا دریافت می‌کنید.
	Id *string `json:"id,omitempty"`
}

// NewPaymentRenewPostBody instantiates a new PaymentRenewPostBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentRenewPostBody() *PaymentRenewPostBody {
	this := PaymentRenewPostBody{}
	return &this
}

// NewPaymentRenewPostBodyWithDefaults instantiates a new PaymentRenewPostBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentRenewPostBodyWithDefaults() *PaymentRenewPostBody {
	this := PaymentRenewPostBody{}
	return &this
}

// GetExtraDetails returns the ExtraDetails field value if set, zero value otherwise.
func (o *PaymentRenewPostBody) GetExtraDetails() string {
	if o == nil || IsNil(o.ExtraDetails) {
		var ret string
		return ret
	}
	return *o.ExtraDetails
}

// GetExtraDetailsOk returns a tuple with the ExtraDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentRenewPostBody) GetExtraDetailsOk() (*string, bool) {
	if o == nil || IsNil(o.ExtraDetails) {
		return nil, false
	}
	return o.ExtraDetails, true
}

// HasExtraDetails returns a boolean if a field has been set.
func (o *PaymentRenewPostBody) HasExtraDetails() bool {
	if o != nil && !IsNil(o.ExtraDetails) {
		return true
	}

	return false
}

// SetExtraDetails gets a reference to the given string and assigns it to the ExtraDetails field.
func (o *PaymentRenewPostBody) SetExtraDetails(v string) {
	o.ExtraDetails = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PaymentRenewPostBody) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentRenewPostBody) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PaymentRenewPostBody) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PaymentRenewPostBody) SetId(v string) {
	o.Id = &v
}

func (o PaymentRenewPostBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentRenewPostBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ExtraDetails) {
		toSerialize["extra_details"] = o.ExtraDetails
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullablePaymentRenewPostBody struct {
	value *PaymentRenewPostBody
	isSet bool
}

func (v NullablePaymentRenewPostBody) Get() *PaymentRenewPostBody {
	return v.value
}

func (v *NullablePaymentRenewPostBody) Set(val *PaymentRenewPostBody) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentRenewPostBody) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentRenewPostBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentRenewPostBody(val *PaymentRenewPostBody) *NullablePaymentRenewPostBody {
	return &NullablePaymentRenewPostBody{value: val, isSet: true}
}

func (v NullablePaymentRenewPostBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentRenewPostBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


