/*
API کنار

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kenarapi

import (
	"encoding/json"
)

// checks if the ChatapiGenerateUploadTokenResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChatapiGenerateUploadTokenResponse{}

// ChatapiGenerateUploadTokenResponse struct for ChatapiGenerateUploadTokenResponse
type ChatapiGenerateUploadTokenResponse struct {
	// توکن با کدگذاری base64 که می‌توان در endpoint آپلود از آن استفاده کرد
	Token *string `json:"token,omitempty"`
}

// NewChatapiGenerateUploadTokenResponse instantiates a new ChatapiGenerateUploadTokenResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChatapiGenerateUploadTokenResponse() *ChatapiGenerateUploadTokenResponse {
	this := ChatapiGenerateUploadTokenResponse{}
	return &this
}

// NewChatapiGenerateUploadTokenResponseWithDefaults instantiates a new ChatapiGenerateUploadTokenResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChatapiGenerateUploadTokenResponseWithDefaults() *ChatapiGenerateUploadTokenResponse {
	this := ChatapiGenerateUploadTokenResponse{}
	return &this
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *ChatapiGenerateUploadTokenResponse) GetToken() string {
	if o == nil || IsNil(o.Token) {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatapiGenerateUploadTokenResponse) GetTokenOk() (*string, bool) {
	if o == nil || IsNil(o.Token) {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *ChatapiGenerateUploadTokenResponse) HasToken() bool {
	if o != nil && !IsNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *ChatapiGenerateUploadTokenResponse) SetToken(v string) {
	o.Token = &v
}

func (o ChatapiGenerateUploadTokenResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChatapiGenerateUploadTokenResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	return toSerialize, nil
}

type NullableChatapiGenerateUploadTokenResponse struct {
	value *ChatapiGenerateUploadTokenResponse
	isSet bool
}

func (v NullableChatapiGenerateUploadTokenResponse) Get() *ChatapiGenerateUploadTokenResponse {
	return v.value
}

func (v *NullableChatapiGenerateUploadTokenResponse) Set(val *ChatapiGenerateUploadTokenResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableChatapiGenerateUploadTokenResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableChatapiGenerateUploadTokenResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChatapiGenerateUploadTokenResponse(val *ChatapiGenerateUploadTokenResponse) *NullableChatapiGenerateUploadTokenResponse {
	return &NullableChatapiGenerateUploadTokenResponse{value: val, isSet: true}
}

func (v NullableChatapiGenerateUploadTokenResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChatapiGenerateUploadTokenResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


