/*
API کنار

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kenarapi

import (
	"encoding/json"
)

// checks if the AddonsUserAddonFilters type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddonsUserAddonFilters{}

// AddonsUserAddonFilters struct for AddonsUserAddonFilters
type AddonsUserAddonFilters struct {
	Categories []string `json:"categories,omitempty"`
}

// NewAddonsUserAddonFilters instantiates a new AddonsUserAddonFilters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddonsUserAddonFilters() *AddonsUserAddonFilters {
	this := AddonsUserAddonFilters{}
	return &this
}

// NewAddonsUserAddonFiltersWithDefaults instantiates a new AddonsUserAddonFilters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddonsUserAddonFiltersWithDefaults() *AddonsUserAddonFilters {
	this := AddonsUserAddonFilters{}
	return &this
}

// GetCategories returns the Categories field value if set, zero value otherwise.
func (o *AddonsUserAddonFilters) GetCategories() []string {
	if o == nil || IsNil(o.Categories) {
		var ret []string
		return ret
	}
	return o.Categories
}

// GetCategoriesOk returns a tuple with the Categories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddonsUserAddonFilters) GetCategoriesOk() ([]string, bool) {
	if o == nil || IsNil(o.Categories) {
		return nil, false
	}
	return o.Categories, true
}

// HasCategories returns a boolean if a field has been set.
func (o *AddonsUserAddonFilters) HasCategories() bool {
	if o != nil && !IsNil(o.Categories) {
		return true
	}

	return false
}

// SetCategories gets a reference to the given []string and assigns it to the Categories field.
func (o *AddonsUserAddonFilters) SetCategories(v []string) {
	o.Categories = v
}

func (o AddonsUserAddonFilters) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddonsUserAddonFilters) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Categories) {
		toSerialize["categories"] = o.Categories
	}
	return toSerialize, nil
}

type NullableAddonsUserAddonFilters struct {
	value *AddonsUserAddonFilters
	isSet bool
}

func (v NullableAddonsUserAddonFilters) Get() *AddonsUserAddonFilters {
	return v.value
}

func (v *NullableAddonsUserAddonFilters) Set(val *AddonsUserAddonFilters) {
	v.value = val
	v.isSet = true
}

func (v NullableAddonsUserAddonFilters) IsSet() bool {
	return v.isSet
}

func (v *NullableAddonsUserAddonFilters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddonsUserAddonFilters(val *AddonsUserAddonFilters) *NullableAddonsUserAddonFilters {
	return &NullableAddonsUserAddonFilters{value: val, isSet: true}
}

func (v NullableAddonsUserAddonFilters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddonsUserAddonFilters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


