/*
divar_interface/open_platform/chatapi/chatapi.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kenarapi

import (
	"encoding/json"
)

// checks if the AddonsOpenServerLink type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddonsOpenServerLink{}

// AddonsOpenServerLink struct for AddonsOpenServerLink
type AddonsOpenServerLink struct {
	Data map[string]interface{} `json:"data,omitempty"`
}

// NewAddonsOpenServerLink instantiates a new AddonsOpenServerLink object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddonsOpenServerLink() *AddonsOpenServerLink {
	this := AddonsOpenServerLink{}
	return &this
}

// NewAddonsOpenServerLinkWithDefaults instantiates a new AddonsOpenServerLink object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddonsOpenServerLinkWithDefaults() *AddonsOpenServerLink {
	this := AddonsOpenServerLink{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *AddonsOpenServerLink) GetData() map[string]interface{} {
	if o == nil || IsNil(o.Data) {
		var ret map[string]interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddonsOpenServerLink) GetDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Data) {
		return map[string]interface{}{}, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *AddonsOpenServerLink) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given map[string]interface{} and assigns it to the Data field.
func (o *AddonsOpenServerLink) SetData(v map[string]interface{}) {
	o.Data = v
}

func (o AddonsOpenServerLink) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddonsOpenServerLink) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableAddonsOpenServerLink struct {
	value *AddonsOpenServerLink
	isSet bool
}

func (v NullableAddonsOpenServerLink) Get() *AddonsOpenServerLink {
	return v.value
}

func (v *NullableAddonsOpenServerLink) Set(val *AddonsOpenServerLink) {
	v.value = val
	v.isSet = true
}

func (v NullableAddonsOpenServerLink) IsSet() bool {
	return v.isSet
}

func (v *NullableAddonsOpenServerLink) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddonsOpenServerLink(val *AddonsOpenServerLink) *NullableAddonsOpenServerLink {
	return &NullableAddonsOpenServerLink{value: val, isSet: true}
}

func (v NullableAddonsOpenServerLink) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddonsOpenServerLink) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


