/*
Kenar API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kenarapi

import (
	"encoding/json"
)

// checks if the EventsGetEventActionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventsGetEventActionRequest{}

// EventsGetEventActionRequest struct for EventsGetEventActionRequest
type EventsGetEventActionRequest struct {
	RequestData *EventsGetEventActionRequestRequestData `json:"request_data,omitempty"`
}

// NewEventsGetEventActionRequest instantiates a new EventsGetEventActionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventsGetEventActionRequest() *EventsGetEventActionRequest {
	this := EventsGetEventActionRequest{}
	return &this
}

// NewEventsGetEventActionRequestWithDefaults instantiates a new EventsGetEventActionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventsGetEventActionRequestWithDefaults() *EventsGetEventActionRequest {
	this := EventsGetEventActionRequest{}
	return &this
}

// GetRequestData returns the RequestData field value if set, zero value otherwise.
func (o *EventsGetEventActionRequest) GetRequestData() EventsGetEventActionRequestRequestData {
	if o == nil || IsNil(o.RequestData) {
		var ret EventsGetEventActionRequestRequestData
		return ret
	}
	return *o.RequestData
}

// GetRequestDataOk returns a tuple with the RequestData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventsGetEventActionRequest) GetRequestDataOk() (*EventsGetEventActionRequestRequestData, bool) {
	if o == nil || IsNil(o.RequestData) {
		return nil, false
	}
	return o.RequestData, true
}

// HasRequestData returns a boolean if a field has been set.
func (o *EventsGetEventActionRequest) HasRequestData() bool {
	if o != nil && !IsNil(o.RequestData) {
		return true
	}

	return false
}

// SetRequestData gets a reference to the given EventsGetEventActionRequestRequestData and assigns it to the RequestData field.
func (o *EventsGetEventActionRequest) SetRequestData(v EventsGetEventActionRequestRequestData) {
	o.RequestData = &v
}

func (o EventsGetEventActionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventsGetEventActionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RequestData) {
		toSerialize["request_data"] = o.RequestData
	}
	return toSerialize, nil
}

type NullableEventsGetEventActionRequest struct {
	value *EventsGetEventActionRequest
	isSet bool
}

func (v NullableEventsGetEventActionRequest) Get() *EventsGetEventActionRequest {
	return v.value
}

func (v *NullableEventsGetEventActionRequest) Set(val *EventsGetEventActionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEventsGetEventActionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEventsGetEventActionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventsGetEventActionRequest(val *EventsGetEventActionRequest) *NullableEventsGetEventActionRequest {
	return &NullableEventsGetEventActionRequest{value: val, isSet: true}
}

func (v NullableEventsGetEventActionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventsGetEventActionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


