/*
Kenar API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kenarapi

import (
	"encoding/json"
)

// checks if the DarvazeVerifyCarOwnershipDelegationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DarvazeVerifyCarOwnershipDelegationResponse{}

// DarvazeVerifyCarOwnershipDelegationResponse struct for DarvazeVerifyCarOwnershipDelegationResponse
type DarvazeVerifyCarOwnershipDelegationResponse struct {
	Id *string `json:"id,omitempty"`
}

// NewDarvazeVerifyCarOwnershipDelegationResponse instantiates a new DarvazeVerifyCarOwnershipDelegationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDarvazeVerifyCarOwnershipDelegationResponse() *DarvazeVerifyCarOwnershipDelegationResponse {
	this := DarvazeVerifyCarOwnershipDelegationResponse{}
	return &this
}

// NewDarvazeVerifyCarOwnershipDelegationResponseWithDefaults instantiates a new DarvazeVerifyCarOwnershipDelegationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDarvazeVerifyCarOwnershipDelegationResponseWithDefaults() *DarvazeVerifyCarOwnershipDelegationResponse {
	this := DarvazeVerifyCarOwnershipDelegationResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DarvazeVerifyCarOwnershipDelegationResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DarvazeVerifyCarOwnershipDelegationResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DarvazeVerifyCarOwnershipDelegationResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DarvazeVerifyCarOwnershipDelegationResponse) SetId(v string) {
	o.Id = &v
}

func (o DarvazeVerifyCarOwnershipDelegationResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DarvazeVerifyCarOwnershipDelegationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableDarvazeVerifyCarOwnershipDelegationResponse struct {
	value *DarvazeVerifyCarOwnershipDelegationResponse
	isSet bool
}

func (v NullableDarvazeVerifyCarOwnershipDelegationResponse) Get() *DarvazeVerifyCarOwnershipDelegationResponse {
	return v.value
}

func (v *NullableDarvazeVerifyCarOwnershipDelegationResponse) Set(val *DarvazeVerifyCarOwnershipDelegationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDarvazeVerifyCarOwnershipDelegationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDarvazeVerifyCarOwnershipDelegationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDarvazeVerifyCarOwnershipDelegationResponse(val *DarvazeVerifyCarOwnershipDelegationResponse) *NullableDarvazeVerifyCarOwnershipDelegationResponse {
	return &NullableDarvazeVerifyCarOwnershipDelegationResponse{value: val, isSet: true}
}

func (v NullableDarvazeVerifyCarOwnershipDelegationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDarvazeVerifyCarOwnershipDelegationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


