/*
API کنار

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kenarapi

import (
	"encoding/json"
)

// checks if the AssetsGetBrandModelsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssetsGetBrandModelsResponse{}

// AssetsGetBrandModelsResponse struct for AssetsGetBrandModelsResponse
type AssetsGetBrandModelsResponse struct {
	BrandModels []AssetsEnumOption `json:"brand_models,omitempty"`
}

// NewAssetsGetBrandModelsResponse instantiates a new AssetsGetBrandModelsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssetsGetBrandModelsResponse() *AssetsGetBrandModelsResponse {
	this := AssetsGetBrandModelsResponse{}
	return &this
}

// NewAssetsGetBrandModelsResponseWithDefaults instantiates a new AssetsGetBrandModelsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssetsGetBrandModelsResponseWithDefaults() *AssetsGetBrandModelsResponse {
	this := AssetsGetBrandModelsResponse{}
	return &this
}

// GetBrandModels returns the BrandModels field value if set, zero value otherwise.
func (o *AssetsGetBrandModelsResponse) GetBrandModels() []AssetsEnumOption {
	if o == nil || IsNil(o.BrandModels) {
		var ret []AssetsEnumOption
		return ret
	}
	return o.BrandModels
}

// GetBrandModelsOk returns a tuple with the BrandModels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsGetBrandModelsResponse) GetBrandModelsOk() ([]AssetsEnumOption, bool) {
	if o == nil || IsNil(o.BrandModels) {
		return nil, false
	}
	return o.BrandModels, true
}

// HasBrandModels returns a boolean if a field has been set.
func (o *AssetsGetBrandModelsResponse) HasBrandModels() bool {
	if o != nil && !IsNil(o.BrandModels) {
		return true
	}

	return false
}

// SetBrandModels gets a reference to the given []AssetsEnumOption and assigns it to the BrandModels field.
func (o *AssetsGetBrandModelsResponse) SetBrandModels(v []AssetsEnumOption) {
	o.BrandModels = v
}

func (o AssetsGetBrandModelsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssetsGetBrandModelsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BrandModels) {
		toSerialize["brand_models"] = o.BrandModels
	}
	return toSerialize, nil
}

type NullableAssetsGetBrandModelsResponse struct {
	value *AssetsGetBrandModelsResponse
	isSet bool
}

func (v NullableAssetsGetBrandModelsResponse) Get() *AssetsGetBrandModelsResponse {
	return v.value
}

func (v *NullableAssetsGetBrandModelsResponse) Set(val *AssetsGetBrandModelsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAssetsGetBrandModelsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAssetsGetBrandModelsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssetsGetBrandModelsResponse(val *AssetsGetBrandModelsResponse) *NullableAssetsGetBrandModelsResponse {
	return &NullableAssetsGetBrandModelsResponse{value: val, isSet: true}
}

func (v NullableAssetsGetBrandModelsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssetsGetBrandModelsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


