/*
divar_interface/open_platform/chatapi/chatapi.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kenarapi

import (
	"encoding/json"
)

// checks if the MessageLocationData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MessageLocationData{}

// MessageLocationData struct for MessageLocationData
type MessageLocationData struct {
	// The latitude in degrees. It must be in the range [-90.0, +90.0].
	Latitude *float64 `json:"latitude,omitempty"`
	// The longitude in degrees. It must be in the range [-180.0, +180.0].
	Longitude *float64 `json:"longitude,omitempty"`
}

// NewMessageLocationData instantiates a new MessageLocationData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMessageLocationData() *MessageLocationData {
	this := MessageLocationData{}
	return &this
}

// NewMessageLocationDataWithDefaults instantiates a new MessageLocationData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMessageLocationDataWithDefaults() *MessageLocationData {
	this := MessageLocationData{}
	return &this
}

// GetLatitude returns the Latitude field value if set, zero value otherwise.
func (o *MessageLocationData) GetLatitude() float64 {
	if o == nil || IsNil(o.Latitude) {
		var ret float64
		return ret
	}
	return *o.Latitude
}

// GetLatitudeOk returns a tuple with the Latitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageLocationData) GetLatitudeOk() (*float64, bool) {
	if o == nil || IsNil(o.Latitude) {
		return nil, false
	}
	return o.Latitude, true
}

// HasLatitude returns a boolean if a field has been set.
func (o *MessageLocationData) HasLatitude() bool {
	if o != nil && !IsNil(o.Latitude) {
		return true
	}

	return false
}

// SetLatitude gets a reference to the given float64 and assigns it to the Latitude field.
func (o *MessageLocationData) SetLatitude(v float64) {
	o.Latitude = &v
}

// GetLongitude returns the Longitude field value if set, zero value otherwise.
func (o *MessageLocationData) GetLongitude() float64 {
	if o == nil || IsNil(o.Longitude) {
		var ret float64
		return ret
	}
	return *o.Longitude
}

// GetLongitudeOk returns a tuple with the Longitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageLocationData) GetLongitudeOk() (*float64, bool) {
	if o == nil || IsNil(o.Longitude) {
		return nil, false
	}
	return o.Longitude, true
}

// HasLongitude returns a boolean if a field has been set.
func (o *MessageLocationData) HasLongitude() bool {
	if o != nil && !IsNil(o.Longitude) {
		return true
	}

	return false
}

// SetLongitude gets a reference to the given float64 and assigns it to the Longitude field.
func (o *MessageLocationData) SetLongitude(v float64) {
	o.Longitude = &v
}

func (o MessageLocationData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MessageLocationData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Latitude) {
		toSerialize["latitude"] = o.Latitude
	}
	if !IsNil(o.Longitude) {
		toSerialize["longitude"] = o.Longitude
	}
	return toSerialize, nil
}

type NullableMessageLocationData struct {
	value *MessageLocationData
	isSet bool
}

func (v NullableMessageLocationData) Get() *MessageLocationData {
	return v.value
}

func (v *NullableMessageLocationData) Set(val *MessageLocationData) {
	v.value = val
	v.isSet = true
}

func (v NullableMessageLocationData) IsSet() bool {
	return v.isSet
}

func (v *NullableMessageLocationData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMessageLocationData(val *MessageLocationData) *NullableMessageLocationData {
	return &NullableMessageLocationData{value: val, isSet: true}
}

func (v NullableMessageLocationData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMessageLocationData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


