/*
API کنار

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kenarapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PostCreateBusinessCustomizedButtonBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostCreateBusinessCustomizedButtonBody{}

// PostCreateBusinessCustomizedButtonBody struct for PostCreateBusinessCustomizedButtonBody
type PostCreateBusinessCustomizedButtonBody struct {
	CustomizedButton PostCustomizedButton `json:"customized_button"`
}

type _PostCreateBusinessCustomizedButtonBody PostCreateBusinessCustomizedButtonBody

// NewPostCreateBusinessCustomizedButtonBody instantiates a new PostCreateBusinessCustomizedButtonBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostCreateBusinessCustomizedButtonBody(customizedButton PostCustomizedButton) *PostCreateBusinessCustomizedButtonBody {
	this := PostCreateBusinessCustomizedButtonBody{}
	this.CustomizedButton = customizedButton
	return &this
}

// NewPostCreateBusinessCustomizedButtonBodyWithDefaults instantiates a new PostCreateBusinessCustomizedButtonBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostCreateBusinessCustomizedButtonBodyWithDefaults() *PostCreateBusinessCustomizedButtonBody {
	this := PostCreateBusinessCustomizedButtonBody{}
	return &this
}

// GetCustomizedButton returns the CustomizedButton field value
func (o *PostCreateBusinessCustomizedButtonBody) GetCustomizedButton() PostCustomizedButton {
	if o == nil {
		var ret PostCustomizedButton
		return ret
	}

	return o.CustomizedButton
}

// GetCustomizedButtonOk returns a tuple with the CustomizedButton field value
// and a boolean to check if the value has been set.
func (o *PostCreateBusinessCustomizedButtonBody) GetCustomizedButtonOk() (*PostCustomizedButton, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomizedButton, true
}

// SetCustomizedButton sets field value
func (o *PostCreateBusinessCustomizedButtonBody) SetCustomizedButton(v PostCustomizedButton) {
	o.CustomizedButton = v
}

func (o PostCreateBusinessCustomizedButtonBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostCreateBusinessCustomizedButtonBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["customized_button"] = o.CustomizedButton
	return toSerialize, nil
}

func (o *PostCreateBusinessCustomizedButtonBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"customized_button",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostCreateBusinessCustomizedButtonBody := _PostCreateBusinessCustomizedButtonBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPostCreateBusinessCustomizedButtonBody)

	if err != nil {
		return err
	}

	*o = PostCreateBusinessCustomizedButtonBody(varPostCreateBusinessCustomizedButtonBody)

	return err
}

type NullablePostCreateBusinessCustomizedButtonBody struct {
	value *PostCreateBusinessCustomizedButtonBody
	isSet bool
}

func (v NullablePostCreateBusinessCustomizedButtonBody) Get() *PostCreateBusinessCustomizedButtonBody {
	return v.value
}

func (v *NullablePostCreateBusinessCustomizedButtonBody) Set(val *PostCreateBusinessCustomizedButtonBody) {
	v.value = val
	v.isSet = true
}

func (v NullablePostCreateBusinessCustomizedButtonBody) IsSet() bool {
	return v.isSet
}

func (v *NullablePostCreateBusinessCustomizedButtonBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostCreateBusinessCustomizedButtonBody(val *PostCreateBusinessCustomizedButtonBody) *NullablePostCreateBusinessCustomizedButtonBody {
	return &NullablePostCreateBusinessCustomizedButtonBody{value: val, isSet: true}
}

func (v NullablePostCreateBusinessCustomizedButtonBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostCreateBusinessCustomizedButtonBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


