/*
API کنار

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kenarapi

import (
	"encoding/json"
)

// checks if the PaymentPublishUserPostBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentPublishUserPostBody{}

// PaymentPublishUserPostBody struct for PaymentPublishUserPostBody
type PaymentPublishUserPostBody struct {
	// جزئیات اضافی که می‌خواهید به سمت کنار ارسال کنید. این فیلد اختیاری است و می‌تواند برای حل ناسازگاری‌ها در تراکنش استفاده شود.
	ExtraDetails *string `json:"extra_details,omitempty"`
	// یک uuid نسخه 4 که باید برای هر پرداخت منحصر به فرد باشد. این uuid باید در سمت شما تولید شده و در درخواست ارسال شود. اگر id ای ارسال شود که تراکنش موفق یا نیمه موفقی در سمت کنار داشته باشد، خطا دریافت خواهید کرد.
	Id *string `json:"id,omitempty"`
}

// NewPaymentPublishUserPostBody instantiates a new PaymentPublishUserPostBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentPublishUserPostBody() *PaymentPublishUserPostBody {
	this := PaymentPublishUserPostBody{}
	return &this
}

// NewPaymentPublishUserPostBodyWithDefaults instantiates a new PaymentPublishUserPostBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentPublishUserPostBodyWithDefaults() *PaymentPublishUserPostBody {
	this := PaymentPublishUserPostBody{}
	return &this
}

// GetExtraDetails returns the ExtraDetails field value if set, zero value otherwise.
func (o *PaymentPublishUserPostBody) GetExtraDetails() string {
	if o == nil || IsNil(o.ExtraDetails) {
		var ret string
		return ret
	}
	return *o.ExtraDetails
}

// GetExtraDetailsOk returns a tuple with the ExtraDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentPublishUserPostBody) GetExtraDetailsOk() (*string, bool) {
	if o == nil || IsNil(o.ExtraDetails) {
		return nil, false
	}
	return o.ExtraDetails, true
}

// HasExtraDetails returns a boolean if a field has been set.
func (o *PaymentPublishUserPostBody) HasExtraDetails() bool {
	if o != nil && !IsNil(o.ExtraDetails) {
		return true
	}

	return false
}

// SetExtraDetails gets a reference to the given string and assigns it to the ExtraDetails field.
func (o *PaymentPublishUserPostBody) SetExtraDetails(v string) {
	o.ExtraDetails = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PaymentPublishUserPostBody) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentPublishUserPostBody) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PaymentPublishUserPostBody) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PaymentPublishUserPostBody) SetId(v string) {
	o.Id = &v
}

func (o PaymentPublishUserPostBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentPublishUserPostBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ExtraDetails) {
		toSerialize["extra_details"] = o.ExtraDetails
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullablePaymentPublishUserPostBody struct {
	value *PaymentPublishUserPostBody
	isSet bool
}

func (v NullablePaymentPublishUserPostBody) Get() *PaymentPublishUserPostBody {
	return v.value
}

func (v *NullablePaymentPublishUserPostBody) Set(val *PaymentPublishUserPostBody) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentPublishUserPostBody) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentPublishUserPostBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentPublishUserPostBody(val *PaymentPublishUserPostBody) *NullablePaymentPublishUserPostBody {
	return &NullablePaymentPublishUserPostBody{value: val, isSet: true}
}

func (v NullablePaymentPublishUserPostBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentPublishUserPostBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


