/*
Kenar API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kenarapi

import (
	"encoding/json"
	"fmt"
)

// TemporaryResidenceFieldsRoomsCount the model 'TemporaryResidenceFieldsRoomsCount'
type TemporaryResidenceFieldsRoomsCount string

// List of TemporaryResidenceFieldsRoomsCount
const (
	TEMPORARYRESIDENCEFIELDSROOMSCOUNT_ROOMS_COUNT_0 TemporaryResidenceFieldsRoomsCount = "ROOMS_COUNT_0"
	TEMPORARYRESIDENCEFIELDSROOMSCOUNT_ROOMS_COUNT_1 TemporaryResidenceFieldsRoomsCount = "ROOMS_COUNT_1"
	TEMPORARYRESIDENCEFIELDSROOMSCOUNT_ROOMS_COUNT_2 TemporaryResidenceFieldsRoomsCount = "ROOMS_COUNT_2"
	TEMPORARYRESIDENCEFIELDSROOMSCOUNT_ROOMS_COUNT_3 TemporaryResidenceFieldsRoomsCount = "ROOMS_COUNT_3"
	TEMPORARYRESIDENCEFIELDSROOMSCOUNT_ROOMS_COUNT_4 TemporaryResidenceFieldsRoomsCount = "ROOMS_COUNT_4"
	TEMPORARYRESIDENCEFIELDSROOMSCOUNT_ROOMS_COUNT_5_OR_MORE TemporaryResidenceFieldsRoomsCount = "ROOMS_COUNT_5_OR_MORE"
)

// All allowed values of TemporaryResidenceFieldsRoomsCount enum
var AllowedTemporaryResidenceFieldsRoomsCountEnumValues = []TemporaryResidenceFieldsRoomsCount{
	"ROOMS_COUNT_0",
	"ROOMS_COUNT_1",
	"ROOMS_COUNT_2",
	"ROOMS_COUNT_3",
	"ROOMS_COUNT_4",
	"ROOMS_COUNT_5_OR_MORE",
}

func (v *TemporaryResidenceFieldsRoomsCount) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TemporaryResidenceFieldsRoomsCount(value)
	for _, existing := range AllowedTemporaryResidenceFieldsRoomsCountEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid TemporaryResidenceFieldsRoomsCount", value)
}

// NewTemporaryResidenceFieldsRoomsCountFromValue returns a pointer to a valid TemporaryResidenceFieldsRoomsCount
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTemporaryResidenceFieldsRoomsCountFromValue(v string) (*TemporaryResidenceFieldsRoomsCount, error) {
	ev := TemporaryResidenceFieldsRoomsCount(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TemporaryResidenceFieldsRoomsCount: valid values are %v", v, AllowedTemporaryResidenceFieldsRoomsCountEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TemporaryResidenceFieldsRoomsCount) IsValid() bool {
	for _, existing := range AllowedTemporaryResidenceFieldsRoomsCountEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to TemporaryResidenceFieldsRoomsCount value
func (v TemporaryResidenceFieldsRoomsCount) Ptr() *TemporaryResidenceFieldsRoomsCount {
	return &v
}

type NullableTemporaryResidenceFieldsRoomsCount struct {
	value *TemporaryResidenceFieldsRoomsCount
	isSet bool
}

func (v NullableTemporaryResidenceFieldsRoomsCount) Get() *TemporaryResidenceFieldsRoomsCount {
	return v.value
}

func (v *NullableTemporaryResidenceFieldsRoomsCount) Set(val *TemporaryResidenceFieldsRoomsCount) {
	v.value = val
	v.isSet = true
}

func (v NullableTemporaryResidenceFieldsRoomsCount) IsSet() bool {
	return v.isSet
}

func (v *NullableTemporaryResidenceFieldsRoomsCount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemporaryResidenceFieldsRoomsCount(val *TemporaryResidenceFieldsRoomsCount) *NullableTemporaryResidenceFieldsRoomsCount {
	return &NullableTemporaryResidenceFieldsRoomsCount{value: val, isSet: true}
}

func (v NullableTemporaryResidenceFieldsRoomsCount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemporaryResidenceFieldsRoomsCount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

