/*
API کنار

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kenarapi

import (
	"encoding/json"
)

// checks if the AssetsGetSubmitSchemaResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssetsGetSubmitSchemaResponse{}

// AssetsGetSubmitSchemaResponse struct for AssetsGetSubmitSchemaResponse
type AssetsGetSubmitSchemaResponse struct {
	Schema map[string]interface{} `json:"schema,omitempty"`
}

// NewAssetsGetSubmitSchemaResponse instantiates a new AssetsGetSubmitSchemaResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssetsGetSubmitSchemaResponse() *AssetsGetSubmitSchemaResponse {
	this := AssetsGetSubmitSchemaResponse{}
	return &this
}

// NewAssetsGetSubmitSchemaResponseWithDefaults instantiates a new AssetsGetSubmitSchemaResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssetsGetSubmitSchemaResponseWithDefaults() *AssetsGetSubmitSchemaResponse {
	this := AssetsGetSubmitSchemaResponse{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *AssetsGetSubmitSchemaResponse) GetSchema() map[string]interface{} {
	if o == nil || IsNil(o.Schema) {
		var ret map[string]interface{}
		return ret
	}
	return o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsGetSubmitSchemaResponse) GetSchemaOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Schema) {
		return map[string]interface{}{}, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *AssetsGetSubmitSchemaResponse) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given map[string]interface{} and assigns it to the Schema field.
func (o *AssetsGetSubmitSchemaResponse) SetSchema(v map[string]interface{}) {
	o.Schema = v
}

func (o AssetsGetSubmitSchemaResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssetsGetSubmitSchemaResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["schema"] = o.Schema
	}
	return toSerialize, nil
}

type NullableAssetsGetSubmitSchemaResponse struct {
	value *AssetsGetSubmitSchemaResponse
	isSet bool
}

func (v NullableAssetsGetSubmitSchemaResponse) Get() *AssetsGetSubmitSchemaResponse {
	return v.value
}

func (v *NullableAssetsGetSubmitSchemaResponse) Set(val *AssetsGetSubmitSchemaResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAssetsGetSubmitSchemaResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAssetsGetSubmitSchemaResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssetsGetSubmitSchemaResponse(val *AssetsGetSubmitSchemaResponse) *NullableAssetsGetSubmitSchemaResponse {
	return &NullableAssetsGetSubmitSchemaResponse{value: val, isSet: true}
}

func (v NullableAssetsGetSubmitSchemaResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssetsGetSubmitSchemaResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


