/*
divar_interface/open_platform/chatapi/chatapi.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kenarapi

import (
	"encoding/json"
)

// checks if the GetServiceTypesResponseServiceTypeData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetServiceTypesResponseServiceTypeData{}

// GetServiceTypesResponseServiceTypeData struct for GetServiceTypesResponseServiceTypeData
type GetServiceTypesResponseServiceTypeData struct {
	Slug *AppsServiceType `json:"slug,omitempty"`
	Display *string `json:"display,omitempty"`
}

// NewGetServiceTypesResponseServiceTypeData instantiates a new GetServiceTypesResponseServiceTypeData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetServiceTypesResponseServiceTypeData() *GetServiceTypesResponseServiceTypeData {
	this := GetServiceTypesResponseServiceTypeData{}
	return &this
}

// NewGetServiceTypesResponseServiceTypeDataWithDefaults instantiates a new GetServiceTypesResponseServiceTypeData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetServiceTypesResponseServiceTypeDataWithDefaults() *GetServiceTypesResponseServiceTypeData {
	this := GetServiceTypesResponseServiceTypeData{}
	return &this
}

// GetSlug returns the Slug field value if set, zero value otherwise.
func (o *GetServiceTypesResponseServiceTypeData) GetSlug() AppsServiceType {
	if o == nil || IsNil(o.Slug) {
		var ret AppsServiceType
		return ret
	}
	return *o.Slug
}

// GetSlugOk returns a tuple with the Slug field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetServiceTypesResponseServiceTypeData) GetSlugOk() (*AppsServiceType, bool) {
	if o == nil || IsNil(o.Slug) {
		return nil, false
	}
	return o.Slug, true
}

// HasSlug returns a boolean if a field has been set.
func (o *GetServiceTypesResponseServiceTypeData) HasSlug() bool {
	if o != nil && !IsNil(o.Slug) {
		return true
	}

	return false
}

// SetSlug gets a reference to the given AppsServiceType and assigns it to the Slug field.
func (o *GetServiceTypesResponseServiceTypeData) SetSlug(v AppsServiceType) {
	o.Slug = &v
}

// GetDisplay returns the Display field value if set, zero value otherwise.
func (o *GetServiceTypesResponseServiceTypeData) GetDisplay() string {
	if o == nil || IsNil(o.Display) {
		var ret string
		return ret
	}
	return *o.Display
}

// GetDisplayOk returns a tuple with the Display field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetServiceTypesResponseServiceTypeData) GetDisplayOk() (*string, bool) {
	if o == nil || IsNil(o.Display) {
		return nil, false
	}
	return o.Display, true
}

// HasDisplay returns a boolean if a field has been set.
func (o *GetServiceTypesResponseServiceTypeData) HasDisplay() bool {
	if o != nil && !IsNil(o.Display) {
		return true
	}

	return false
}

// SetDisplay gets a reference to the given string and assigns it to the Display field.
func (o *GetServiceTypesResponseServiceTypeData) SetDisplay(v string) {
	o.Display = &v
}

func (o GetServiceTypesResponseServiceTypeData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetServiceTypesResponseServiceTypeData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Slug) {
		toSerialize["slug"] = o.Slug
	}
	if !IsNil(o.Display) {
		toSerialize["display"] = o.Display
	}
	return toSerialize, nil
}

type NullableGetServiceTypesResponseServiceTypeData struct {
	value *GetServiceTypesResponseServiceTypeData
	isSet bool
}

func (v NullableGetServiceTypesResponseServiceTypeData) Get() *GetServiceTypesResponseServiceTypeData {
	return v.value
}

func (v *NullableGetServiceTypesResponseServiceTypeData) Set(val *GetServiceTypesResponseServiceTypeData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetServiceTypesResponseServiceTypeData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetServiceTypesResponseServiceTypeData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetServiceTypesResponseServiceTypeData(val *GetServiceTypesResponseServiceTypeData) *NullableGetServiceTypesResponseServiceTypeData {
	return &NullableGetServiceTypesResponseServiceTypeData{value: val, isSet: true}
}

func (v NullableGetServiceTypesResponseServiceTypeData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetServiceTypesResponseServiceTypeData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


