/*
Kenar API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kenarapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ChatAPIChatBotSendMessageBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChatAPIChatBotSendMessageBody{}

// ChatAPIChatBotSendMessageBody struct for ChatAPIChatBotSendMessageBody
type ChatAPIChatBotSendMessageBody struct {
	// Unique identifier for the user to start or continue a conversation with
	UserId *string `json:"user_id,omitempty"`
	// Text message content to be sent by the bot
	TextMessage string `json:"text_message"`
	// Token for attached media (if any)
	MediaToken *string `json:"media_token,omitempty"`
	Buttons *ChatapiChatButtonGrid `json:"buttons,omitempty"`
}

type _ChatAPIChatBotSendMessageBody ChatAPIChatBotSendMessageBody

// NewChatAPIChatBotSendMessageBody instantiates a new ChatAPIChatBotSendMessageBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChatAPIChatBotSendMessageBody(textMessage string) *ChatAPIChatBotSendMessageBody {
	this := ChatAPIChatBotSendMessageBody{}
	this.TextMessage = textMessage
	return &this
}

// NewChatAPIChatBotSendMessageBodyWithDefaults instantiates a new ChatAPIChatBotSendMessageBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChatAPIChatBotSendMessageBodyWithDefaults() *ChatAPIChatBotSendMessageBody {
	this := ChatAPIChatBotSendMessageBody{}
	return &this
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *ChatAPIChatBotSendMessageBody) GetUserId() string {
	if o == nil || IsNil(o.UserId) {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatAPIChatBotSendMessageBody) GetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *ChatAPIChatBotSendMessageBody) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *ChatAPIChatBotSendMessageBody) SetUserId(v string) {
	o.UserId = &v
}

// GetTextMessage returns the TextMessage field value
func (o *ChatAPIChatBotSendMessageBody) GetTextMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TextMessage
}

// GetTextMessageOk returns a tuple with the TextMessage field value
// and a boolean to check if the value has been set.
func (o *ChatAPIChatBotSendMessageBody) GetTextMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TextMessage, true
}

// SetTextMessage sets field value
func (o *ChatAPIChatBotSendMessageBody) SetTextMessage(v string) {
	o.TextMessage = v
}

// GetMediaToken returns the MediaToken field value if set, zero value otherwise.
func (o *ChatAPIChatBotSendMessageBody) GetMediaToken() string {
	if o == nil || IsNil(o.MediaToken) {
		var ret string
		return ret
	}
	return *o.MediaToken
}

// GetMediaTokenOk returns a tuple with the MediaToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatAPIChatBotSendMessageBody) GetMediaTokenOk() (*string, bool) {
	if o == nil || IsNil(o.MediaToken) {
		return nil, false
	}
	return o.MediaToken, true
}

// HasMediaToken returns a boolean if a field has been set.
func (o *ChatAPIChatBotSendMessageBody) HasMediaToken() bool {
	if o != nil && !IsNil(o.MediaToken) {
		return true
	}

	return false
}

// SetMediaToken gets a reference to the given string and assigns it to the MediaToken field.
func (o *ChatAPIChatBotSendMessageBody) SetMediaToken(v string) {
	o.MediaToken = &v
}

// GetButtons returns the Buttons field value if set, zero value otherwise.
func (o *ChatAPIChatBotSendMessageBody) GetButtons() ChatapiChatButtonGrid {
	if o == nil || IsNil(o.Buttons) {
		var ret ChatapiChatButtonGrid
		return ret
	}
	return *o.Buttons
}

// GetButtonsOk returns a tuple with the Buttons field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatAPIChatBotSendMessageBody) GetButtonsOk() (*ChatapiChatButtonGrid, bool) {
	if o == nil || IsNil(o.Buttons) {
		return nil, false
	}
	return o.Buttons, true
}

// HasButtons returns a boolean if a field has been set.
func (o *ChatAPIChatBotSendMessageBody) HasButtons() bool {
	if o != nil && !IsNil(o.Buttons) {
		return true
	}

	return false
}

// SetButtons gets a reference to the given ChatapiChatButtonGrid and assigns it to the Buttons field.
func (o *ChatAPIChatBotSendMessageBody) SetButtons(v ChatapiChatButtonGrid) {
	o.Buttons = &v
}

func (o ChatAPIChatBotSendMessageBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChatAPIChatBotSendMessageBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UserId) {
		toSerialize["user_id"] = o.UserId
	}
	toSerialize["text_message"] = o.TextMessage
	if !IsNil(o.MediaToken) {
		toSerialize["media_token"] = o.MediaToken
	}
	if !IsNil(o.Buttons) {
		toSerialize["buttons"] = o.Buttons
	}
	return toSerialize, nil
}

func (o *ChatAPIChatBotSendMessageBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"text_message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChatAPIChatBotSendMessageBody := _ChatAPIChatBotSendMessageBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varChatAPIChatBotSendMessageBody)

	if err != nil {
		return err
	}

	*o = ChatAPIChatBotSendMessageBody(varChatAPIChatBotSendMessageBody)

	return err
}

type NullableChatAPIChatBotSendMessageBody struct {
	value *ChatAPIChatBotSendMessageBody
	isSet bool
}

func (v NullableChatAPIChatBotSendMessageBody) Get() *ChatAPIChatBotSendMessageBody {
	return v.value
}

func (v *NullableChatAPIChatBotSendMessageBody) Set(val *ChatAPIChatBotSendMessageBody) {
	v.value = val
	v.isSet = true
}

func (v NullableChatAPIChatBotSendMessageBody) IsSet() bool {
	return v.isSet
}

func (v *NullableChatAPIChatBotSendMessageBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChatAPIChatBotSendMessageBody(val *ChatAPIChatBotSendMessageBody) *NullableChatAPIChatBotSendMessageBody {
	return &NullableChatAPIChatBotSendMessageBody{value: val, isSet: true}
}

func (v NullableChatAPIChatBotSendMessageBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChatAPIChatBotSendMessageBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


