/*
Kenar API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kenarapi

import (
	"encoding/json"
)

// checks if the AddonsButtonBar type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddonsButtonBar{}

// AddonsButtonBar struct for AddonsButtonBar
type AddonsButtonBar struct {
	Action *AddonsAction `json:"action,omitempty"`
	Title *string `json:"title,omitempty"`
}

// NewAddonsButtonBar instantiates a new AddonsButtonBar object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddonsButtonBar() *AddonsButtonBar {
	this := AddonsButtonBar{}
	return &this
}

// NewAddonsButtonBarWithDefaults instantiates a new AddonsButtonBar object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddonsButtonBarWithDefaults() *AddonsButtonBar {
	this := AddonsButtonBar{}
	return &this
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *AddonsButtonBar) GetAction() AddonsAction {
	if o == nil || IsNil(o.Action) {
		var ret AddonsAction
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddonsButtonBar) GetActionOk() (*AddonsAction, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *AddonsButtonBar) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given AddonsAction and assigns it to the Action field.
func (o *AddonsButtonBar) SetAction(v AddonsAction) {
	o.Action = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *AddonsButtonBar) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddonsButtonBar) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *AddonsButtonBar) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *AddonsButtonBar) SetTitle(v string) {
	o.Title = &v
}

func (o AddonsButtonBar) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddonsButtonBar) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	return toSerialize, nil
}

type NullableAddonsButtonBar struct {
	value *AddonsButtonBar
	isSet bool
}

func (v NullableAddonsButtonBar) Get() *AddonsButtonBar {
	return v.value
}

func (v *NullableAddonsButtonBar) Set(val *AddonsButtonBar) {
	v.value = val
	v.isSet = true
}

func (v NullableAddonsButtonBar) IsSet() bool {
	return v.isSet
}

func (v *NullableAddonsButtonBar) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddonsButtonBar(val *AddonsButtonBar) *NullableAddonsButtonBar {
	return &NullableAddonsButtonBar{value: val, isSet: true}
}

func (v NullableAddonsButtonBar) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddonsButtonBar) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


