/*
divar_interface/open_platform/chatapi/chatapi.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kenarapi

import (
	"encoding/json"
)

// checks if the PaymentTicketGenerateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentTicketGenerateResponse{}

// PaymentTicketGenerateResponse struct for PaymentTicketGenerateResponse
type PaymentTicketGenerateResponse struct {
	TicketUuid *string `json:"ticket_uuid,omitempty"`
}

// NewPaymentTicketGenerateResponse instantiates a new PaymentTicketGenerateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentTicketGenerateResponse() *PaymentTicketGenerateResponse {
	this := PaymentTicketGenerateResponse{}
	return &this
}

// NewPaymentTicketGenerateResponseWithDefaults instantiates a new PaymentTicketGenerateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentTicketGenerateResponseWithDefaults() *PaymentTicketGenerateResponse {
	this := PaymentTicketGenerateResponse{}
	return &this
}

// GetTicketUuid returns the TicketUuid field value if set, zero value otherwise.
func (o *PaymentTicketGenerateResponse) GetTicketUuid() string {
	if o == nil || IsNil(o.TicketUuid) {
		var ret string
		return ret
	}
	return *o.TicketUuid
}

// GetTicketUuidOk returns a tuple with the TicketUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentTicketGenerateResponse) GetTicketUuidOk() (*string, bool) {
	if o == nil || IsNil(o.TicketUuid) {
		return nil, false
	}
	return o.TicketUuid, true
}

// HasTicketUuid returns a boolean if a field has been set.
func (o *PaymentTicketGenerateResponse) HasTicketUuid() bool {
	if o != nil && !IsNil(o.TicketUuid) {
		return true
	}

	return false
}

// SetTicketUuid gets a reference to the given string and assigns it to the TicketUuid field.
func (o *PaymentTicketGenerateResponse) SetTicketUuid(v string) {
	o.TicketUuid = &v
}

func (o PaymentTicketGenerateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentTicketGenerateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TicketUuid) {
		toSerialize["ticket_uuid"] = o.TicketUuid
	}
	return toSerialize, nil
}

type NullablePaymentTicketGenerateResponse struct {
	value *PaymentTicketGenerateResponse
	isSet bool
}

func (v NullablePaymentTicketGenerateResponse) Get() *PaymentTicketGenerateResponse {
	return v.value
}

func (v *NullablePaymentTicketGenerateResponse) Set(val *PaymentTicketGenerateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentTicketGenerateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentTicketGenerateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentTicketGenerateResponse(val *PaymentTicketGenerateResponse) *NullablePaymentTicketGenerateResponse {
	return &NullablePaymentTicketGenerateResponse{value: val, isSet: true}
}

func (v NullablePaymentTicketGenerateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentTicketGenerateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


