/*
divar_interface/open_platform/chatapi/chatapi.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kenarapi

import (
	"encoding/json"
)

// checks if the ChatAPIChatBotSendMessageBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChatAPIChatBotSendMessageBody{}

// ChatAPIChatBotSendMessageBody struct for ChatAPIChatBotSendMessageBody
type ChatAPIChatBotSendMessageBody struct {
	UserId *string `json:"user_id,omitempty"`
	TextMessage *string `json:"text_message,omitempty"`
	MediaToken *string `json:"media_token,omitempty"`
	Buttons *ChatapiChatButtonGrid `json:"buttons,omitempty"`
}

// NewChatAPIChatBotSendMessageBody instantiates a new ChatAPIChatBotSendMessageBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChatAPIChatBotSendMessageBody() *ChatAPIChatBotSendMessageBody {
	this := ChatAPIChatBotSendMessageBody{}
	return &this
}

// NewChatAPIChatBotSendMessageBodyWithDefaults instantiates a new ChatAPIChatBotSendMessageBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChatAPIChatBotSendMessageBodyWithDefaults() *ChatAPIChatBotSendMessageBody {
	this := ChatAPIChatBotSendMessageBody{}
	return &this
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *ChatAPIChatBotSendMessageBody) GetUserId() string {
	if o == nil || IsNil(o.UserId) {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatAPIChatBotSendMessageBody) GetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *ChatAPIChatBotSendMessageBody) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *ChatAPIChatBotSendMessageBody) SetUserId(v string) {
	o.UserId = &v
}

// GetTextMessage returns the TextMessage field value if set, zero value otherwise.
func (o *ChatAPIChatBotSendMessageBody) GetTextMessage() string {
	if o == nil || IsNil(o.TextMessage) {
		var ret string
		return ret
	}
	return *o.TextMessage
}

// GetTextMessageOk returns a tuple with the TextMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatAPIChatBotSendMessageBody) GetTextMessageOk() (*string, bool) {
	if o == nil || IsNil(o.TextMessage) {
		return nil, false
	}
	return o.TextMessage, true
}

// HasTextMessage returns a boolean if a field has been set.
func (o *ChatAPIChatBotSendMessageBody) HasTextMessage() bool {
	if o != nil && !IsNil(o.TextMessage) {
		return true
	}

	return false
}

// SetTextMessage gets a reference to the given string and assigns it to the TextMessage field.
func (o *ChatAPIChatBotSendMessageBody) SetTextMessage(v string) {
	o.TextMessage = &v
}

// GetMediaToken returns the MediaToken field value if set, zero value otherwise.
func (o *ChatAPIChatBotSendMessageBody) GetMediaToken() string {
	if o == nil || IsNil(o.MediaToken) {
		var ret string
		return ret
	}
	return *o.MediaToken
}

// GetMediaTokenOk returns a tuple with the MediaToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatAPIChatBotSendMessageBody) GetMediaTokenOk() (*string, bool) {
	if o == nil || IsNil(o.MediaToken) {
		return nil, false
	}
	return o.MediaToken, true
}

// HasMediaToken returns a boolean if a field has been set.
func (o *ChatAPIChatBotSendMessageBody) HasMediaToken() bool {
	if o != nil && !IsNil(o.MediaToken) {
		return true
	}

	return false
}

// SetMediaToken gets a reference to the given string and assigns it to the MediaToken field.
func (o *ChatAPIChatBotSendMessageBody) SetMediaToken(v string) {
	o.MediaToken = &v
}

// GetButtons returns the Buttons field value if set, zero value otherwise.
func (o *ChatAPIChatBotSendMessageBody) GetButtons() ChatapiChatButtonGrid {
	if o == nil || IsNil(o.Buttons) {
		var ret ChatapiChatButtonGrid
		return ret
	}
	return *o.Buttons
}

// GetButtonsOk returns a tuple with the Buttons field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatAPIChatBotSendMessageBody) GetButtonsOk() (*ChatapiChatButtonGrid, bool) {
	if o == nil || IsNil(o.Buttons) {
		return nil, false
	}
	return o.Buttons, true
}

// HasButtons returns a boolean if a field has been set.
func (o *ChatAPIChatBotSendMessageBody) HasButtons() bool {
	if o != nil && !IsNil(o.Buttons) {
		return true
	}

	return false
}

// SetButtons gets a reference to the given ChatapiChatButtonGrid and assigns it to the Buttons field.
func (o *ChatAPIChatBotSendMessageBody) SetButtons(v ChatapiChatButtonGrid) {
	o.Buttons = &v
}

func (o ChatAPIChatBotSendMessageBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChatAPIChatBotSendMessageBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UserId) {
		toSerialize["user_id"] = o.UserId
	}
	if !IsNil(o.TextMessage) {
		toSerialize["text_message"] = o.TextMessage
	}
	if !IsNil(o.MediaToken) {
		toSerialize["media_token"] = o.MediaToken
	}
	if !IsNil(o.Buttons) {
		toSerialize["buttons"] = o.Buttons
	}
	return toSerialize, nil
}

type NullableChatAPIChatBotSendMessageBody struct {
	value *ChatAPIChatBotSendMessageBody
	isSet bool
}

func (v NullableChatAPIChatBotSendMessageBody) Get() *ChatAPIChatBotSendMessageBody {
	return v.value
}

func (v *NullableChatAPIChatBotSendMessageBody) Set(val *ChatAPIChatBotSendMessageBody) {
	v.value = val
	v.isSet = true
}

func (v NullableChatAPIChatBotSendMessageBody) IsSet() bool {
	return v.isSet
}

func (v *NullableChatAPIChatBotSendMessageBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChatAPIChatBotSendMessageBody(val *ChatAPIChatBotSendMessageBody) *NullableChatAPIChatBotSendMessageBody {
	return &NullableChatAPIChatBotSendMessageBody{value: val, isSet: true}
}

func (v NullableChatAPIChatBotSendMessageBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChatAPIChatBotSendMessageBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


