/*
divar_interface/open_platform/chatapi/chatapi.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kenarapi

import (
	"encoding/json"
)

// checks if the ChatapiGetConversationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChatapiGetConversationResponse{}

// ChatapiGetConversationResponse struct for ChatapiGetConversationResponse
type ChatapiGetConversationResponse struct {
	Conversation *ChatapiConversation `json:"conversation,omitempty"`
	Messages []ChatapiMessage `json:"messages,omitempty"`
}

// NewChatapiGetConversationResponse instantiates a new ChatapiGetConversationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChatapiGetConversationResponse() *ChatapiGetConversationResponse {
	this := ChatapiGetConversationResponse{}
	return &this
}

// NewChatapiGetConversationResponseWithDefaults instantiates a new ChatapiGetConversationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChatapiGetConversationResponseWithDefaults() *ChatapiGetConversationResponse {
	this := ChatapiGetConversationResponse{}
	return &this
}

// GetConversation returns the Conversation field value if set, zero value otherwise.
func (o *ChatapiGetConversationResponse) GetConversation() ChatapiConversation {
	if o == nil || IsNil(o.Conversation) {
		var ret ChatapiConversation
		return ret
	}
	return *o.Conversation
}

// GetConversationOk returns a tuple with the Conversation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatapiGetConversationResponse) GetConversationOk() (*ChatapiConversation, bool) {
	if o == nil || IsNil(o.Conversation) {
		return nil, false
	}
	return o.Conversation, true
}

// HasConversation returns a boolean if a field has been set.
func (o *ChatapiGetConversationResponse) HasConversation() bool {
	if o != nil && !IsNil(o.Conversation) {
		return true
	}

	return false
}

// SetConversation gets a reference to the given ChatapiConversation and assigns it to the Conversation field.
func (o *ChatapiGetConversationResponse) SetConversation(v ChatapiConversation) {
	o.Conversation = &v
}

// GetMessages returns the Messages field value if set, zero value otherwise.
func (o *ChatapiGetConversationResponse) GetMessages() []ChatapiMessage {
	if o == nil || IsNil(o.Messages) {
		var ret []ChatapiMessage
		return ret
	}
	return o.Messages
}

// GetMessagesOk returns a tuple with the Messages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatapiGetConversationResponse) GetMessagesOk() ([]ChatapiMessage, bool) {
	if o == nil || IsNil(o.Messages) {
		return nil, false
	}
	return o.Messages, true
}

// HasMessages returns a boolean if a field has been set.
func (o *ChatapiGetConversationResponse) HasMessages() bool {
	if o != nil && !IsNil(o.Messages) {
		return true
	}

	return false
}

// SetMessages gets a reference to the given []ChatapiMessage and assigns it to the Messages field.
func (o *ChatapiGetConversationResponse) SetMessages(v []ChatapiMessage) {
	o.Messages = v
}

func (o ChatapiGetConversationResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChatapiGetConversationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Conversation) {
		toSerialize["conversation"] = o.Conversation
	}
	if !IsNil(o.Messages) {
		toSerialize["messages"] = o.Messages
	}
	return toSerialize, nil
}

type NullableChatapiGetConversationResponse struct {
	value *ChatapiGetConversationResponse
	isSet bool
}

func (v NullableChatapiGetConversationResponse) Get() *ChatapiGetConversationResponse {
	return v.value
}

func (v *NullableChatapiGetConversationResponse) Set(val *ChatapiGetConversationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableChatapiGetConversationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableChatapiGetConversationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChatapiGetConversationResponse(val *ChatapiGetConversationResponse) *NullableChatapiGetConversationResponse {
	return &NullableChatapiGetConversationResponse{value: val, isSet: true}
}

func (v NullableChatapiGetConversationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChatapiGetConversationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


