/*
Kenar API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kenarapi

import (
	"encoding/json"
)

// checks if the PaymentGetBalanceResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentGetBalanceResponse{}

// PaymentGetBalanceResponse struct for PaymentGetBalanceResponse
type PaymentGetBalanceResponse struct {
	// The balance of the app in rials
	BalanceRials *string `json:"balance_rials,omitempty"`
}

// NewPaymentGetBalanceResponse instantiates a new PaymentGetBalanceResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentGetBalanceResponse() *PaymentGetBalanceResponse {
	this := PaymentGetBalanceResponse{}
	return &this
}

// NewPaymentGetBalanceResponseWithDefaults instantiates a new PaymentGetBalanceResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentGetBalanceResponseWithDefaults() *PaymentGetBalanceResponse {
	this := PaymentGetBalanceResponse{}
	return &this
}

// GetBalanceRials returns the BalanceRials field value if set, zero value otherwise.
func (o *PaymentGetBalanceResponse) GetBalanceRials() string {
	if o == nil || IsNil(o.BalanceRials) {
		var ret string
		return ret
	}
	return *o.BalanceRials
}

// GetBalanceRialsOk returns a tuple with the BalanceRials field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentGetBalanceResponse) GetBalanceRialsOk() (*string, bool) {
	if o == nil || IsNil(o.BalanceRials) {
		return nil, false
	}
	return o.BalanceRials, true
}

// HasBalanceRials returns a boolean if a field has been set.
func (o *PaymentGetBalanceResponse) HasBalanceRials() bool {
	if o != nil && !IsNil(o.BalanceRials) {
		return true
	}

	return false
}

// SetBalanceRials gets a reference to the given string and assigns it to the BalanceRials field.
func (o *PaymentGetBalanceResponse) SetBalanceRials(v string) {
	o.BalanceRials = &v
}

func (o PaymentGetBalanceResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentGetBalanceResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BalanceRials) {
		toSerialize["balance_rials"] = o.BalanceRials
	}
	return toSerialize, nil
}

type NullablePaymentGetBalanceResponse struct {
	value *PaymentGetBalanceResponse
	isSet bool
}

func (v NullablePaymentGetBalanceResponse) Get() *PaymentGetBalanceResponse {
	return v.value
}

func (v *NullablePaymentGetBalanceResponse) Set(val *PaymentGetBalanceResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentGetBalanceResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentGetBalanceResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentGetBalanceResponse(val *PaymentGetBalanceResponse) *NullablePaymentGetBalanceResponse {
	return &NullablePaymentGetBalanceResponse{value: val, isSet: true}
}

func (v NullablePaymentGetBalanceResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentGetBalanceResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


