/*
divar_interface/open_platform/chatapi/chatapi.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kenarapi

import (
	"encoding/json"
)

// checks if the AssetsGetCitiesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssetsGetCitiesResponse{}

// AssetsGetCitiesResponse struct for AssetsGetCitiesResponse
type AssetsGetCitiesResponse struct {
	Cities []AssetsEnumOption `json:"cities,omitempty"`
}

// NewAssetsGetCitiesResponse instantiates a new AssetsGetCitiesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssetsGetCitiesResponse() *AssetsGetCitiesResponse {
	this := AssetsGetCitiesResponse{}
	return &this
}

// NewAssetsGetCitiesResponseWithDefaults instantiates a new AssetsGetCitiesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssetsGetCitiesResponseWithDefaults() *AssetsGetCitiesResponse {
	this := AssetsGetCitiesResponse{}
	return &this
}

// GetCities returns the Cities field value if set, zero value otherwise.
func (o *AssetsGetCitiesResponse) GetCities() []AssetsEnumOption {
	if o == nil || IsNil(o.Cities) {
		var ret []AssetsEnumOption
		return ret
	}
	return o.Cities
}

// GetCitiesOk returns a tuple with the Cities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsGetCitiesResponse) GetCitiesOk() ([]AssetsEnumOption, bool) {
	if o == nil || IsNil(o.Cities) {
		return nil, false
	}
	return o.Cities, true
}

// HasCities returns a boolean if a field has been set.
func (o *AssetsGetCitiesResponse) HasCities() bool {
	if o != nil && !IsNil(o.Cities) {
		return true
	}

	return false
}

// SetCities gets a reference to the given []AssetsEnumOption and assigns it to the Cities field.
func (o *AssetsGetCitiesResponse) SetCities(v []AssetsEnumOption) {
	o.Cities = v
}

func (o AssetsGetCitiesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssetsGetCitiesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Cities) {
		toSerialize["cities"] = o.Cities
	}
	return toSerialize, nil
}

type NullableAssetsGetCitiesResponse struct {
	value *AssetsGetCitiesResponse
	isSet bool
}

func (v NullableAssetsGetCitiesResponse) Get() *AssetsGetCitiesResponse {
	return v.value
}

func (v *NullableAssetsGetCitiesResponse) Set(val *AssetsGetCitiesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAssetsGetCitiesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAssetsGetCitiesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssetsGetCitiesResponse(val *AssetsGetCitiesResponse) *NullableAssetsGetCitiesResponse {
	return &NullableAssetsGetCitiesResponse{value: val, isSet: true}
}

func (v NullableAssetsGetCitiesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssetsGetCitiesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


