/*
divar_interface/open_platform/chatapi/chatapi.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kenarapi

import (
	"encoding/json"
)

// checks if the AssetsGetBodyStatusesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssetsGetBodyStatusesResponse{}

// AssetsGetBodyStatusesResponse struct for AssetsGetBodyStatusesResponse
type AssetsGetBodyStatusesResponse struct {
	BodyStatus []AssetsEnumOption `json:"body_status,omitempty"`
}

// NewAssetsGetBodyStatusesResponse instantiates a new AssetsGetBodyStatusesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssetsGetBodyStatusesResponse() *AssetsGetBodyStatusesResponse {
	this := AssetsGetBodyStatusesResponse{}
	return &this
}

// NewAssetsGetBodyStatusesResponseWithDefaults instantiates a new AssetsGetBodyStatusesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssetsGetBodyStatusesResponseWithDefaults() *AssetsGetBodyStatusesResponse {
	this := AssetsGetBodyStatusesResponse{}
	return &this
}

// GetBodyStatus returns the BodyStatus field value if set, zero value otherwise.
func (o *AssetsGetBodyStatusesResponse) GetBodyStatus() []AssetsEnumOption {
	if o == nil || IsNil(o.BodyStatus) {
		var ret []AssetsEnumOption
		return ret
	}
	return o.BodyStatus
}

// GetBodyStatusOk returns a tuple with the BodyStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsGetBodyStatusesResponse) GetBodyStatusOk() ([]AssetsEnumOption, bool) {
	if o == nil || IsNil(o.BodyStatus) {
		return nil, false
	}
	return o.BodyStatus, true
}

// HasBodyStatus returns a boolean if a field has been set.
func (o *AssetsGetBodyStatusesResponse) HasBodyStatus() bool {
	if o != nil && !IsNil(o.BodyStatus) {
		return true
	}

	return false
}

// SetBodyStatus gets a reference to the given []AssetsEnumOption and assigns it to the BodyStatus field.
func (o *AssetsGetBodyStatusesResponse) SetBodyStatus(v []AssetsEnumOption) {
	o.BodyStatus = v
}

func (o AssetsGetBodyStatusesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssetsGetBodyStatusesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BodyStatus) {
		toSerialize["body_status"] = o.BodyStatus
	}
	return toSerialize, nil
}

type NullableAssetsGetBodyStatusesResponse struct {
	value *AssetsGetBodyStatusesResponse
	isSet bool
}

func (v NullableAssetsGetBodyStatusesResponse) Get() *AssetsGetBodyStatusesResponse {
	return v.value
}

func (v *NullableAssetsGetBodyStatusesResponse) Set(val *AssetsGetBodyStatusesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAssetsGetBodyStatusesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAssetsGetBodyStatusesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssetsGetBodyStatusesResponse(val *AssetsGetBodyStatusesResponse) *NullableAssetsGetBodyStatusesResponse {
	return &NullableAssetsGetBodyStatusesResponse{value: val, isSet: true}
}

func (v NullableAssetsGetBodyStatusesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssetsGetBodyStatusesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


